export const deckOfCards: Array<ICard> = [
  {
    suit: "club",
    cardValue: "A",
    colour: "black",
    suitRank: 1,
  },
  {
    suit: "club",
    cardValue: "2",
    colour: "black",
    suitRank: 2,
  },
  {
    suit: "club",
    cardValue: "3",
    colour: "black",
    suitRank: 3,
  },
  {
    suit: "club",
    cardValue: "4",
    colour: "black",
    suitRank: 4,
  },
  {
    suit: "club",
    cardValue: "5",
    colour: "black",
    suitRank: 5,
  },
  {
    suit: "club",
    cardValue: "6",
    colour: "black",
    suitRank: 6,
  },
  {
    suit: "club",
    cardValue: "7",
    colour: "black",
    suitRank: 7,
  },
  {
    suit: "club",
    cardValue: "8",
    colour: "black",
    suitRank: 8,
  },
  {
    suit: "club",
    cardValue: "9",
    colour: "black",
    suitRank: 9,
  },
  {
    suit: "club",
    cardValue: "10",
    colour: "black",
    suitRank: 10,
  },
  {
    suit: "club",
    cardValue: "J",
    colour: "black",
    suitRank: 11,
  },
  {
    suit: "club",
    cardValue: "Q",
    colour: "black",
    suitRank: 12,
  },
  {
    suit: "club",
    cardValue: "K",
    colour: "black",
    suitRank: 13,
  },
  {
    suit: "diamond",
    cardValue: "A",
    colour: "red",
    suitRank: 1,
  },
  {
    suit: "diamond",
    cardValue: "2",
    colour: "red",
    suitRank: 2,
  },
  {
    suit: "diamond",
    cardValue: "3",
    colour: "red",
    suitRank: 3,
  },
  {
    suit: "diamond",
    cardValue: "4",
    colour: "red",
    suitRank: 4,
  },
  {
    suit: "diamond",
    cardValue: "5",
    colour: "red",
    suitRank: 5,
  },
  {
    suit: "diamond",
    cardValue: "6",
    colour: "red",
    suitRank: 6,
  },
  {
    suit: "diamond",
    cardValue: "7",
    colour: "red",
    suitRank: 7,
  },
  {
    suit: "diamond",
    cardValue: "8",
    colour: "red",
    suitRank: 8,
  },
  {
    suit: "diamond",
    cardValue: "9",
    colour: "red",
    suitRank: 9,
  },
  {
    suit: "diamond",
    cardValue: "10",
    colour: "red",
    suitRank: 10,
  },
  {
    suit: "diamond",
    cardValue: "J",
    colour: "red",
    suitRank: 11,
  },
  {
    suit: "diamond",
    cardValue: "Q",
    colour: "red",
    suitRank: 12,
  },
  {
    suit: "diamond",
    cardValue: "K",
    colour: "red",
    suitRank: 13,
  },
  {
    suit: "heart",
    cardValue: "A",
    colour: "red",
    suitRank: 1,
  },
  {
    suit: "heart",
    cardValue: "2",
    colour: "red",
    suitRank: 2,
  },
  {
    suit: "heart",
    cardValue: "3",
    colour: "red",
    suitRank: 3,
  },
  {
    suit: "heart",
    cardValue: "4",
    colour: "red",
    suitRank: 4,
  },
  {
    suit: "heart",
    cardValue: "5",
    colour: "red",
    suitRank: 5,
  },
  {
    suit: "heart",
    cardValue: "6",
    colour: "red",
    suitRank: 6,
  },
  {
    suit: "heart",
    cardValue: "7",
    colour: "red",
    suitRank: 7,
  },
  {
    suit: "heart",
    cardValue: "8",
    colour: "red",
    suitRank: 8,
  },
  {
    suit: "heart",
    cardValue: "9",
    colour: "red",
    suitRank: 9,
  },
  {
    suit: "heart",
    cardValue: "10",
    colour: "red",
    suitRank: 10,
  },
  {
    suit: "heart",
    cardValue: "J",
    colour: "red",
    suitRank: 11,
  },
  {
    suit: "heart",
    cardValue: "Q",
    colour: "red",
    suitRank: 12,
  },
  {
    suit: "heart",
    cardValue: "K",
    colour: "red",
    suitRank: 13,
  },
  {
    suit: "spade",
    cardValue: "A",
    colour: "black",
    suitRank: 1,
  },
  {
    suit: "spade",
    cardValue: "2",
    colour: "black",
    suitRank: 2,
  },
  {
    suit: "spade",
    cardValue: "3",
    colour: "black",
    suitRank: 3,
  },
  {
    suit: "spade",
    cardValue: "4",
    colour: "black",
    suitRank: 4,
  },
  {
    suit: "spade",
    cardValue: "5",
    colour: "black",
    suitRank: 5,
  },
  {
    suit: "spade",
    cardValue: "6",
    colour: "black",
    suitRank: 6,
  },
  {
    suit: "spade",
    cardValue: "7",
    colour: "black",
    suitRank: 7,
  },
  {
    suit: "spade",
    cardValue: "8",
    colour: "black",
    suitRank: 8,
  },
  {
    suit: "spade",
    cardValue: "9",
    colour: "black",
    suitRank: 9,
  },
  {
    suit: "spade",
    cardValue: "10",
    colour: "black",
    suitRank: 10,
  },
  {
    suit: "spade",
    cardValue: "J",
    colour: "black",
    suitRank: 11,
  },
  {
    suit: "spade",
    cardValue: "Q",
    colour: "black",
    suitRank: 12,
  },
  {
    suit: "spade",
    cardValue: "K",
    colour: "black",
    suitRank: 13,
  },
];
